const houses=[
{id:1,area:"新潟県三条市",name:"まちなか移住ハウス",people:4,price:2500,features:["Wi-Fi","駐車場","仕事スペース"],icon:"🏡",station:"東三条駅から車で8分",desc:"商店街と市街地に近く、仕事と暮らしを体験しやすい住宅です。",plan:"2泊3日・企業見学プラン"},
{id:2,area:"新潟県燕市",name:"子育て体験住宅",people:5,price:3000,features:["Wi-Fi","駐車場","子ども用品"],icon:"🏠",station:"燕三条駅から車で15分",desc:"保育園や学校、スーパーを巡る家族向けの滞在住宅です。",plan:"3泊4日・子育て環境体験"},
{id:3,area:"長野県飯山市",name:"雪国里山ハウス",people:6,price:2200,features:["Wi-Fi","駐車場","ペット可"],icon:"🏔️",station:"飯山駅から車で20分",desc:"自然と農のある暮らしを体験できる広い一戸建てです。",plan:"6泊7日・農業体験プラン"},
{id:4,area:"富山県南砺市",name:"古民家つながり庵",people:8,price:2800,features:["Wi-Fi","駐車場","ペット可"],icon:"🌾",station:"福光駅から車で12分",desc:"地域交流や古民家暮らしを体験できる里山の住宅です。",plan:"4泊5日・地域交流プラン"},
{id:5,area:"新潟県三条市",name:"ものづくり滞在室",people:2,price:2000,features:["Wi-Fi","仕事スペース"],icon:"🔨",station:"北三条駅から徒歩10分",desc:"工場見学やテレワークに便利なコンパクト住宅です。",plan:"2泊3日・仕事体験プラン"},
{id:6,area:"新潟県燕市",name:"田園ファミリーハウス",people:6,price:3200,features:["Wi-Fi","駐車場","子ども用品"],icon:"🌱",station:"吉田駅から車で10分",desc:"田園と市街地の両方を感じられる家族向け住宅です。",plan:"5泊6日・暮らし体験プラン"}];
const supports=[
{area:"三条市",type:"移住",name:"移住・就業支援金",amount:"最大100万円",desc:"東京圏からの移住と対象求人への就業など、一定の要件を満たす世帯向け。"},
{area:"燕市",type:"住宅",name:"空き家改修費補助",amount:"最大50万円",desc:"空き家バンク登録住宅の改修費の一部を支援する想定制度。"},
{area:"飯山市",type:"子育て",name:"子育て世帯移住応援",amount:"最大30万円",desc:"18歳未満の子どもがいる移住世帯を支援する想定制度。"},
{area:"南砺市",type:"起業",name:"地域起業チャレンジ補助",amount:"最大80万円",desc:"地域課題の解決につながる事業の創業費を支援する想定制度。"}];
const mapData={
"三条市":{q:"新潟県三条市",facilities:[["🏥","済生会新潟県央基幹病院","車で約12分"],["🛒","スーパーマーケット","車で約5分"],["🏫","小中学校","徒歩・車で5〜15分"],["📷","燕三条地場産業振興センター","車で約15分"]],access:"上越新幹線・燕三条駅、JR東三条駅を利用できます。東京駅から燕三条駅まで新幹線で約2時間。市内移動は車が便利です。"},
"燕市":{q:"新潟県燕市",facilities:[["🏥","県立吉田病院","車で約10分"],["🛒","ショッピングセンター","車で約8分"],["🏫","保育園・学校","車で5〜15分"],["📷","燕市産業史料館","車で約12分"]],access:"上越新幹線・燕三条駅から市内へ車で約15分。JR越後線・弥彦線も利用できます。"},
"飯山市":{q:"長野県飯山市",facilities:[["🏥","飯山赤十字病院","車で約10分"],["🛒","スーパー","車で約8分"],["🏫","学校・保育園","車で10〜20分"],["📷","斑尾高原","車で約25分"]],access:"北陸新幹線・飯山駅を利用できます。東京駅から約1時間40分。冬季は雪道への備えが必要です。"},
"南砺市":{q:"富山県南砺市",facilities:[["🏥","南砺市民病院","車で約15分"],["🛒","スーパー","車で約10分"],["🏫","学校・保育園","車で10〜20分"],["📷","五箇山合掌造り集落","車で約35分"]],access:"北陸新幹線・新高岡駅から車で約40分。市内は路線バスと自家用車の併用が便利です。"}};
const regions=[
{name:"三条市",emoji:"🔨",copy:"ものづくりと自然が近いまち",bg:"linear-gradient(135deg,#3d735d,#85aa79)"},
{name:"燕市",emoji:"🍴",copy:"金属加工と子育てのまち",bg:"linear-gradient(135deg,#506d83,#9aaeb8)"},
{name:"飯山市",emoji:"🏔️",copy:"雪と農、アウトドアの暮らし",bg:"linear-gradient(135deg,#36556b,#83a9b9)"},
{name:"南砺市",emoji:"🌾",copy:"古民家と地域交流の里山",bg:"linear-gradient(135deg,#6e5c3d,#a5946d)"}];
const translations={ja:{navHome:"ホーム",navHouses:"お試し住宅",navMap:"地図・交通",navRegion:"地域紹介",navSupport:"支援制度",navCost:"生活費計算",navDiagnosis:"自治体診断",navMypage:"マイページ",heroTitle:"あなたに合う地域と<br>お試し住宅を見つけよう。",heroText:"住宅、交通、生活費、支援制度をまとめて比較し、移住前の不安を減らします。",searchHouse:"住宅を探す",startDiagnosis:"自治体診断を始める"},en:{navHome:"Home",navHouses:"Trial homes",navMap:"Map & access",navRegion:"Regions",navSupport:"Support",navCost:"Living costs",navDiagnosis:"Matching",navMypage:"My page",heroTitle:"Find a region and<br>trial home for you.",heroText:"Compare housing, access, costs and support before moving.",searchHouse:"Find homes",startDiagnosis:"Start matching"},zh:{navHome:"首页",navHouses:"体验住宅",navMap:"地图交通",navRegion:"地区介绍",navSupport:"支援制度",navCost:"生活费计算",navDiagnosis:"地区诊断",navMypage:"我的页面",heroTitle:"寻找适合您的地区<br>和体验住宅。",heroText:"比较住宅、交通、生活费和支援制度。",searchHouse:"搜索住宅",startDiagnosis:"开始诊断"}};
let favorites=JSON.parse(localStorage.getItem("ijuV2Favorites")||"[]");
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2000)}
function changeView(name){$$(".view").forEach(v=>v.classList.remove("active"));$("#view-"+name).classList.add("active");$("#sideNav").classList.remove("open");scrollTo({top:0,behavior:"smooth"});if(name==="favorites")renderFavorites();if(name==="mypage")renderMyPage()}
$$("[data-view]").forEach(b=>b.addEventListener("click",()=>changeView(b.dataset.view)));
$("#menuBtn").addEventListener("click",()=>$("#sideNav").classList.toggle("open"));
function cardHTML(h){return `<article class="house-card"><div class="house-photo"><span class="area-label">${h.area}</span><button class="fav" data-fav="${h.id}">${favorites.includes(h.id)?"♥":"♡"}</button>${h.icon}</div><div class="house-body"><div class="chips">${h.features.map(f=>`<span class="chip">${f}</span>`).join("")}</div><h3>${h.name}</h3><p>${h.desc}</p><div class="house-meta"><span>👥 最大${h.people}名</span><span>💴 1泊 ${h.price.toLocaleString()}円</span><span>🚃 ${h.station}</span></div><div class="house-actions"><button class="secondary" data-detail="${h.id}">詳細</button><button class="primary" data-plan="${h.id}">プラン保存</button></div></div></article>`}
function bindCards(){$$("[data-fav]").forEach(b=>b.onclick=()=>toggleFav(Number(b.dataset.fav)));$$("[data-detail]").forEach(b=>b.onclick=()=>showDetail(Number(b.dataset.detail)));$$("[data-plan]").forEach(b=>b.onclick=()=>savePlan(Number(b.dataset.plan)))}
function renderHome(){ $("#homeRecommendations").innerHTML=houses.slice(0,3).map(cardHTML).join("");bindCards()}
function renderHouses(){let k=$("#houseKeyword").value.toLowerCase(),a=$("#areaFilter").value,p=Number($("#peopleFilter").value),f=$("#featureFilter").value;let list=houses.filter(h=>(!k||(h.name+h.area).toLowerCase().includes(k))&&(a==="all"||h.area===a)&&(!p||h.people>=p)&&(f==="all"||h.features.includes(f)));$("#houseCount").textContent=`${list.length}件の住宅`;$("#houseGrid").innerHTML=list.length?list.map(cardHTML).join(""):`<div class="content-card">条件に合う住宅がありません。</div>`;bindCards()}
["houseKeyword","areaFilter","peopleFilter","featureFilter"].forEach(id=>$("#"+id).addEventListener(id==="houseKeyword"?"input":"change",renderHouses));
$("#clearFilters").onclick=()=>{$("#houseKeyword").value="";$("#areaFilter").value="all";$("#peopleFilter").value="0";$("#featureFilter").value="all";renderHouses()};
function toggleFav(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem("ijuV2Favorites",JSON.stringify(favorites));$("#favCount").textContent=favorites.length;renderHome();renderHouses();renderFavorites();toast(favorites.includes(id)?"お気に入りに保存しました":"お気に入りから削除しました")}
function renderFavorites(){let list=houses.filter(h=>favorites.includes(h.id));$("#favoriteGrid").innerHTML=list.length?list.map(cardHTML).join(""):`<div class="content-card">お気に入りはまだありません。</div>`;bindCards()}
function showDetail(id){let h=houses.find(x=>x.id===id);$("#modalContent").innerHTML=`<div class="modal-hero">${h.icon}</div><h2>${h.name}</h2><p>${h.area}</p><p>${h.desc}</p><div class="chips">${h.features.map(f=>`<span class="chip">${f}</span>`).join("")}</div><h3>おすすめ滞在プラン</h3><p>${h.plan}</p><h3>料金</h3><p>1泊 ${h.price.toLocaleString()}円／最大${h.people}名</p><h3>交通</h3><p>${h.station}</p><button class="primary wide" onclick="savePlan(${h.id});document.querySelector('#houseModal').classList.add('hidden')">このプランを保存</button>`;$("#houseModal").classList.remove("hidden")}
$("#modalClose").onclick=()=>$("#houseModal").classList.add("hidden");$("#houseModal").onclick=e=>{if(e.target.id==="houseModal")$("#houseModal").classList.add("hidden")};
function savePlan(id){let h=houses.find(x=>x.id===id);localStorage.setItem("ijuV2Plan",JSON.stringify(h));toast("おすすめプランをマイページに保存しました")}
function updateMap(){let d=mapData[$("#mapAreaSelect").value];$("#mapFrame").src=`https://www.google.com/maps?q=${encodeURIComponent(d.q)}&output=embed`;$("#facilityList").innerHTML=d.facilities.map(x=>`<div class="facility"><b>${x[0]} ${x[1]}</b><small>${x[2]}</small></div>`).join("");$("#accessInfo").textContent=d.access}
$("#mapAreaSelect").onchange=updateMap;
function renderRegions(){$("#regionGrid").innerHTML=regions.map(r=>`<article class="region-card" style="background:${r.bg}"><span style="font-size:50px">${r.emoji}</span><h2>${r.name}</h2><p>${r.copy}</p></article>`).join("")}
$("#playVideo").onclick=()=>{let t=$("#videoText");t.textContent="▶ 住宅見学 → 仕事相談 → 地域交流 → 振り返り";toast("紹介スライドを再生しました")};
function renderSupports(){let a=$("#supportArea").value,t=$("#supportType").value;let list=supports.filter(s=>(a==="all"||s.area===a)&&(t==="all"||s.type===t));$("#supportGrid").innerHTML=list.map(s=>`<article class="support-card"><div><div class="chips"><span class="chip">${s.area}</span><span class="chip">${s.type}</span></div><h3>${s.name}</h3><p>${s.desc}</p></div><strong>${s.amount}</strong></article>`).join("")}
$("#supportArea").onchange=renderSupports;$("#supportType").onchange=renderSupports;
function calcCost(){let ids=["rent","food","utility","transport","communication","other"];let labels=["家賃","食費","光熱費","交通・車両費","通信費","その他"];let vals=ids.map(id=>Number($("#"+id).value)||0),total=vals.reduce((a,b)=>a+b,0);$("#monthlyTotal").textContent="¥"+total.toLocaleString();$("#annualTotal").textContent="¥"+(total*12).toLocaleString();$("#costBreakdown").innerHTML=labels.map((l,i)=>`<div><span>${l}</span><b>¥${vals[i].toLocaleString()}</b></div>`).join("");return {total,vals,people:Number($("#costPeople").value)}}
$$("#costForm input").forEach(i=>i.addEventListener("input",calcCost));
$("#saveSimulation").onclick=()=>{localStorage.setItem("ijuV2Cost",JSON.stringify(calcCost()));toast("生活費試算を保存しました")};
$("#diagnosisForm").onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target).entries());let city="三条市",house=houses[0],reason="仕事と生活の利便性のバランスが良く、ものづくり企業との出会いがあります。";if(d.purpose==="family"){city="燕市";house=houses[1];reason="子育て施設と市街地の暮らしやすさを重視する世帯に向いています。"}else if(d.purpose==="agri"||d.environment==="nature"){city="飯山市";house=houses[2];reason="農業、自然、広い住まいを体験したい方におすすめです。"}else if(d.house==="old"){city="南砺市";house=houses[3];reason="古民家と地域交流を重視する暮らしに向いています。"}let result={city,houseId:house.id,reason,date:new Date().toLocaleDateString("ja-JP")};localStorage.setItem("ijuV2Diagnosis",JSON.stringify(result));$("#diagnosisResult").innerHTML=`<span class="result-icon">🎯</span><span class="eyebrow">BEST MATCH</span><h2>${city}</h2><p>${reason}</p><div class="recommend-house"><b>${house.name}</b><br>${house.plan}<br>1泊 ${house.price.toLocaleString()}円〜</div><button class="primary" onclick="savePlan(${house.id})">プランを保存</button>`};
$("#profileForm").onsubmit=e=>{e.preventDefault();let p={name:$("#profileName").value,email:$("#profileEmail").value,timing:$("#profileTiming").value};localStorage.setItem("ijuV2Profile",JSON.stringify(p));toast("プロフィールを保存しました");renderMyPage()};
function renderMyPage(){let p=JSON.parse(localStorage.getItem("ijuV2Profile")||"{}"),d=JSON.parse(localStorage.getItem("ijuV2Diagnosis")||"null"),c=JSON.parse(localStorage.getItem("ijuV2Cost")||"null"),plan=JSON.parse(localStorage.getItem("ijuV2Plan")||"null");$("#profileName").value=p.name||"";$("#profileEmail").value=p.email||"";$("#profileTiming").value=p.timing||"未定";$("#mypageSummary").innerHTML=`<div><b>お気に入り</b><br>${favorites.length}件</div><div><b>自治体診断</b><br>${d?d.city+"（"+d.date+"）":"未診断"}</div><div><b>保存プラン</b><br>${plan?plan.name:"未保存"}</div><div><b>生活費試算</b><br>${c?"月額 ¥"+c.total.toLocaleString():"未保存"}</div>`}
$("#clearMyData").onclick=()=>{if(confirm("保存データをすべて削除しますか？")){["ijuV2Favorites","ijuV2Plan","ijuV2Cost","ijuV2Diagnosis","ijuV2Profile"].forEach(k=>localStorage.removeItem(k));favorites=[];location.reload()}};
$("#languageSelect").onchange=e=>{let lang=e.target.value,t=translations[lang];$$("[data-i18n]").forEach(el=>{let v=t[el.dataset.i18n];if(v!==undefined)el.innerHTML=v});localStorage.setItem("ijuV2Lang",lang);toast(lang==="ja"?"日本語に切り替えました":lang==="en"?"Switched to English":"已切换为中文")};
let lang=localStorage.getItem("ijuV2Lang")||"ja";$("#languageSelect").value=lang;$("#languageSelect").dispatchEvent(new Event("change"));
renderHome();renderHouses();renderFavorites();renderRegions();renderSupports();updateMap();calcCost();renderMyPage();$("#favCount").textContent=favorites.length;
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
