const areas=[
 {name:'新潟県 三条市',type:'仕事',desc:'ものづくり産業と自然が近く、地方で働きながら暮らしを試したい人向け。',features:['ものづくり','温泉','新幹線アクセス']},
 {name:'新潟県 燕市',type:'仕事',desc:'金属加工のまち。工場見学や地域企業との交流を重視した滞在に。',features:['産業体験','移住相談','生活利便性']},
 {name:'長野県 飯山市',type:'自然',desc:'山と雪のある暮らしを体験。冬の生活や車移動を確かめたい人向け。',features:['雪国体験','自然','テレワーク']},
 {name:'富山県 南砺市',type:'自然',desc:'里山文化と地域交流を体験できる、落ち着いた暮らしの候補地。',features:['里山','空き家','地域交流']},
 {name:'群馬県 みなかみ町',type:'自然',desc:'アウトドアや温泉を楽しみながら、観光地域での仕事も確認できます。',features:['温泉','観光','アウトドア']},
 {name:'福井県 鯖江市',type:'子育て',desc:'コンパクトなまちで、仕事、教育、買い物の距離感を確認しやすい地域。',features:['子育て','IT','ものづくり']}
];
const defaults=['自治体のお試し住宅の空き状況を確認','利用条件・費用を確認','本人確認書類を準備','交通手段を予約','現地相談の予約','仕事・住まいの質問をまとめる'];
let tasks=JSON.parse(localStorage.getItem('ijuTasks')||'null')||defaults.map((text,i)=>({id:Date.now()+i,text,done:false}));
let favorites=JSON.parse(localStorage.getItem('ijuFavorites')||'[]');
let plans=JSON.parse(localStorage.getItem('ijuPlans')||'[]');
const save=()=>{localStorage.setItem('ijuTasks',JSON.stringify(tasks));localStorage.setItem('ijuFavorites',JSON.stringify(favorites));localStorage.setItem('ijuPlans',JSON.stringify(plans));updateStats()};
function renderAreas(){const q=document.querySelector('#searchInput').value.toLowerCase();const type=document.querySelector('#typeFilter').value;const list=areas.filter(a=>(type==='all'||a.type===type)&&(a.name+a.desc+a.features.join('')).toLowerCase().includes(q));document.querySelector('#areaList').innerHTML=list.map(a=>`<article class="card"><div class="card-top"><span class="tag">${a.type}重視</span><h3>${a.name}</h3></div><div class="card-body"><p>${a.desc}</p><div class="features">${a.features.map(f=>`<span>${f}</span>`).join('')}</div><button class="fav ${favorites.includes(a.name)?'active':''}" data-name="${a.name}">${favorites.includes(a.name)?'★ お気に入り済み':'☆ お気に入り'}</button></div></article>`).join('')||'<p>該当する候補地がありません。</p>';document.querySelectorAll('.fav').forEach(b=>b.onclick=()=>{const n=b.dataset.name;favorites=favorites.includes(n)?favorites.filter(x=>x!==n):[...favorites,n];save();renderAreas()})}
function renderTasks(){document.querySelector('#taskList').innerHTML=tasks.map(t=>`<label class="task ${t.done?'done':''}"><input type="checkbox" ${t.done?'checked':''} data-id="${t.id}"><span>${t.text}</span><button type="button" data-del="${t.id}">×</button></label>`).join('');document.querySelectorAll('[data-id]').forEach(el=>el.onchange=()=>{tasks=tasks.map(t=>t.id==el.dataset.id?{...t,done:el.checked}:t);save();renderTasks()});document.querySelectorAll('[data-del]').forEach(el=>el.onclick=()=>{tasks=tasks.filter(t=>t.id!=el.dataset.del);save();renderTasks()})}
function renderPlans(){document.querySelector('#planList').innerHTML=plans.map(p=>`<article class="plan"><div><h3>${p.area}</h3><p>${p.start} 〜 ${p.end}</p>${p.memo?`<p>${p.memo}</p>`:''}</div><button data-plan-del="${p.id}">削除</button></article>`).join('')||'<p class="empty">まだ予定は登録されていません。</p>';document.querySelectorAll('[data-plan-del]').forEach(b=>b.onclick=()=>{plans=plans.filter(p=>p.id!=b.dataset.planDel);save();renderPlans()})}
function updateStats(){document.querySelector('#favoriteCount').textContent=favorites.length;document.querySelector('#taskCount').textContent=tasks.filter(t=>t.done).length;document.querySelector('#planCount').textContent=plans.length}
document.querySelector('#searchInput').addEventListener('input',renderAreas);document.querySelector('#typeFilter').addEventListener('change',renderAreas);document.querySelector('#addTask').onclick=()=>{const input=document.querySelector('#newTask');if(!input.value.trim())return;tasks.push({id:Date.now(),text:input.value.trim(),done:false});input.value='';save();renderTasks()};document.querySelector('#resetTasks').onclick=()=>{tasks=defaults.map((text,i)=>({id:Date.now()+i,text,done:false}));save();renderTasks()};document.querySelector('#planForm').onsubmit=e=>{e.preventDefault();plans.unshift({id:Date.now(),area:planArea.value,start:startDate.value,end:endDate.value,memo:memo.value.trim()});e.target.reset();save();renderPlans()};
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});installBtn.onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.hidden=true};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');renderAreas();renderTasks();renderPlans();updateStats();
